spring:
  datasource:
    url: jdbc:postgresql:localhost:5432/d6e5rrgadig6gm
    username: postgresql
    password: postgresql
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: catequese-backend
server:
  port: 8081